# Generated by Django 5.2.1 on 2025-08-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('growth_plan', models.CharField(choices=[('Minimal-Growth', 'Minimal-Growth'), ('Standard-Growth', 'Standard-Growth'), ('Explosive-Growth', 'Explosive-Growth')], max_length=32)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consent', models.BooleanField(default=False)),
            ],
        ),
    ]
